# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-02 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0004_auto_20180502_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ecountry',
            field=models.CharField(default=0, max_length=250, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='event',
            name='estate',
            field=models.CharField(default=0, max_length=250, verbose_name='State'),
        ),
    ]
